### ISSUE TITLE
Can't INSTALL plugin it show doesn't suport on 4.20

### ISSUE THREAD

**Issue by mykaimono** [cabbage89/Nop.Plugin.DropShipping.AliExpress.Doc#1]
![support](https://user-images.githubusercontent.com/72932578/96148119-edfd7100-0f42-11eb-9b2c-3c9fc71a4fb4.png)

Please check attached screenshot. Better please send us 4.30 version support plugin. didn't get any email reply also

**Comment by cabbage89** [comment]
I'm very sorry, the plugin supports version 4.3, the source code is already included, and it is very easy to support 4.2. I will package a version that supports 4.2 for you later

**Comment by cabbage89** [comment]
You can modify the plugin.json file
"SupportedVersions": ["4.20" ],
then rebuild the plug with Visual Stadio

**Comment by STS15** [comment]
A 4.3 version for me would also be great

**Comment by cabbage89** [comment]
![image](https://user-images.githubusercontent.com/5857950/96362390-722c4000-115f-11eb-878b-751b87268cb3.png)
Due to the very big difference between 4.2 and 4.3, I refactored the entire project and now it works well on 4.2

**Comment by mykaimono** [comment]
thank you
